easy_admin:
    formats:
        date:     'd/m/Y'
        datetime: 'd/m/Y'
    design:
        menu:
            - { label: 'Homepage', url: '/', rel: 'index' }
            - label: 'Product'
              children: ['Product', 'ProductCategory']
            - label: 'Order'
              children: ['Order']
            - label: 'User'
              children: ['User']
            - label: 'BidHistory'
              children: ['BidHistory']
            - label: 'News'
              children: ['News']
    entities:

        Product:
            class: App\Entity\Product
            label: 'Лот'
            list:
                actions: ['active', 'hide']
                fields:
                    - {property: 'id' , label: 'ID'}
                    - {property: 'name' , label: 'Name', type: 'string'}
                    - {property: 'code' , label: 'Code', type: 'string'}
                    - {property: 'price' , label: 'Price'}
                    - {property: 'category.name' , label: 'Category'}
                    - {property: 'status' , label: 'Status'}
                    - {property: 'photo', label: 'Photo', type: 'image', base_path: '/images/products' }
            form:
                fields:
                    - { type: 'group' , label: 'Basic Information' }
                    - 'name'
                    - 'code'
                    - 'category'
                    - 'owner'
                    - 'price'
                    - { type: 'group', label: 'About Information', icon: 'info' }
                    - { property: 'about', type: 'fos_ckeditor'}
                    - { property: 'startAt', format: 'd/n/Y'}
                    - { property: 'finishAt', format: 'd/m/Y'}
                    - { type: 'group', label: 'Photo Information', icon: 'photo' }
                    - { property: 'photoFile', type: 'vich_file' }

            templates:
                edit: 'admin/Product/edit.html.twig'
                new: 'admin/Product/new.html.twig'

        ProductCategory:
            class: App\Entity\ProductCategory
            label: 'Категория'
            list:
                dql_filter: 'entity.parent IS NULL'
                fields: ['id', 'name']
            form:
                fields: ['name']


        User:
            class: App\Entity\User
            list:
                actions: ['show']
                fields:
                    - {property: 'id' , label: 'ID'}
                    - {property: 'username' , label: 'username', type: 'string'}
                    - {property: 'firstName' , label: 'First name', type: 'string'}
                    - {property: 'lastName' , label: 'Last name', type: 'string'}
                    - {property: 'email' , label: 'email'}
                    - {property: 'phone' , label: 'phone'}
                    - {property: 'address' , label: 'address'}
                    - {property: 'roles' , label: 'roles'}
                    - {property: 'enabled' , label: 'Enabled'}
                    - {property: 'status' , label: 'status'}
                    - {property: 'identificCode' , label: 'identificCode'}
            form:
                fields:
                    - 'firstName'
                    - 'lastName'
                    - 'email'
                    - 'password'
                    - 'address'
                    - 'roles'
                    - 'status'
                    - 'identificCode'
        Order:
            class: App\Entity\Order
            label: 'Order'
            list:
                fields:
                    - {property: 'id' , label: 'ID'}
                    - {property: 'price' , label: 'price'}
                    - {property: 'paymentDetails' , label: 'paymentDetails'}
                    - {property: 'status' , label: 'status'}
            form:
                fields:
                    - 'price'
                    - 'paymentDetails'
                    - 'status'

        BidHistory:
            class: App\Entity\BidHistory
            label: 'BidHistory'
            list:
                fields:
                    - {property: 'id' , label: 'ID'}
                    - {property: 'bidTime' , label: 'bidTime'}
                    - {property: 'bidAmount' , label: 'bidAmount'}
            form:
                fields:
                    - 'bidTime'
                    - 'bidAmount'

        News:
            class: App\Entity\News
            label: 'News'
            list:
                actions: ['show']
                fields:
                    - {property: 'id' , label: 'ID'}

                    - {property: 'title' , label: 'title'}
                    - {property: 'description' , label: 'description'}
                    - {property: 'date' , label: 'date'}
                    - {property: 'enable' , label: 'enable'}
            form:
                fields:
                    - 'id'
                    - { property: 'date', format: 'd/n/Y'}
                    - { property: 'title'}
                    - { property: 'enable'}
                    - { property: 'description', type: 'fos_ckeditor'}
